// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddForwardRule(arg1) {
  return window['go']['main']['App']['AddForwardRule'](arg1);
}

export function AllowInboundPort(arg1) {
  return window['go']['main']['App']['AllowInboundPort'](arg1);
}

export function ConnectPeer(arg1) {
  return window['go']['main']['App']['ConnectPeer'](arg1);
}

export function DisallowInboundPort(arg1) {
  return window['go']['main']['App']['DisallowInboundPort'](arg1);
}

export function GenerateRandomKey() {
  return window['go']['main']['App']['GenerateRandomKey']();
}

export function GetForwardRules() {
  return window['go']['main']['App']['GetForwardRules']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function JoinNetwork(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['JoinNetwork'](arg1, arg2, arg3, arg4, arg5);
}

export function LeaveNetwork() {
  return window['go']['main']['App']['LeaveNetwork']();
}

export function RemoveForwardRule(arg1) {
  return window['go']['main']['App']['RemoveForwardRule'](arg1);
}

export function SetFirewallMode(arg1) {
  return window['go']['main']['App']['SetFirewallMode'](arg1);
}
