// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {p2p} from '../models';
import {main} from '../models';

export function AddForwardRule(arg1:proxy.ForwardingRule):Promise<void>;

export function AllowInboundPort(arg1:number):Promise<void>;

export function ConnectPeer(arg1:string):Promise<void>;

export function DisallowInboundPort(arg1:number):Promise<void>;

export function GenerateRandomKey():Promise<string>;

export function GetForwardRules():Promise<Array<proxy.ForwardingRule>>;

export function GetPeers():Promise<Array<p2p.Peer>>;

export function GetStatus():Promise<main.ConnectionStatus>;

export function JoinNetwork(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<main.ConnectionStatus>;

export function LeaveNetwork():Promise<void>;

export function RemoveForwardRule(arg1:string):Promise<void>;

export function SetFirewallMode(arg1:string):Promise<void>;

export function SetNetworkMode(arg1:string):Promise<void>;
